In [1]:
import numpy as np


In [11]:
a1 = np.array([1,2,3,4])
# a1
# a1.dtype
a1.shape

(4,)

In [15]:
a2 = np.array([5,6,7,8])
# a2*2
# a1*a2
a1 + a2

array([ 6,  8, 10, 12])

In [6]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np

In [3]:
x = [i for i in range(10)]
y = [i for i in range(10)]

print(x,y)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
X = np.array(x)
Y = np.array(y)

print(X)
print(Y)
print(X,Y)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [12]:
X = np.array(x).reshape((-1,1))
Y = np.array(y).reshape((-1,1))

print(X)
print()
print(Y)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
lin_regressor = LinearRegression()
lin_regressor.fit(X,Y)
Y_pred = lin_regressor.predict(X)